# ... existing code ...
from django.urls import path, include  # added include

urlpatterns = [
    # ... existing routes ...
    path('purchase/', include('goldsilverpurchase.urls')),  # added
]
# ... existing code ...