from django import forms
from django.core.exceptions import ValidationError
from nepali_datetime_field.forms import NepaliDateField
from decimal import Decimal
from .models import Ornament
import nepali_datetime as ndt


class OrnamentForm(forms.ModelForm):

    ornament_date = NepaliDateField(required=False)
    jarti = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        required=False
    )

    class Meta:
        model = Ornament
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Set default date to today's Nepali date for new instances
        if not self.instance.pk and not self.initial.get('ornament_date'):
            self.initial['ornament_date'] = ndt.date.today()

        # Set default status for new instances
        if not self.instance.pk and not self.initial.get('status'):
            self.initial['status'] = 'active'

        # Set default values for new ornament instances
        if not self.instance.pk:
            # Set initial values
            default_fields = {
                'gross_weight': Decimal('0.0'),
                'weight': Decimal('0.0'),
                'diamond_weight': Decimal('0.0'),
                'diamond_rate': Decimal('0.0'),
                'zircon_weight': Decimal('0.0'),
                'stone_weight': Decimal('0.0'),
                'stone_percaratprice': Decimal('0.0'),
                'stone_totalprice': Decimal('0.0'),
                'jarti': Decimal('0.0'),
                'jyala': Decimal('0.0'),
            }
            
            for field_name, default_value in default_fields.items():
                if not self.initial.get(field_name):
                    self.initial[field_name] = default_value
                
                # Also set the widget value to display 0.0 in the field
                if field_name in self.fields:
                    self.fields[field_name].widget.attrs['value'] = '0.0'

        # Code is auto-generated
        if 'code' in self.fields:
            self.fields['code'].required = False
            self.fields['code'].widget.attrs.update({
                'class': 'form-control bg-light',
                'placeholder': 'Code (auto-generated)',
            })

    def save(self, commit=True):
        """Preserve or backfill ornament code when saving.

        - New ornaments: code is generated by the post_save signal if blank.
        - Existing ornaments: keep existing code if present; if it's blank,
          generate a code based on the current field values and existing `pk`.
        """

        instance = super().save(commit=False)

        # For existing objects, ensure they have a code
        if instance.pk:
            if not instance.code:
                name_letter = instance.ornament_name[0].upper() if instance.ornament_name else "X"
                sub_category = instance.subcategory.name[0].upper() if instance.subcategory else "X"
                main_category = instance.maincategory.name[0].upper() if instance.maincategory else "X"
                kaligar_letter = instance.kaligar.name[0].upper() if instance.kaligar else "X"
                ornament_type_letter = instance.ornament_type[0].upper() if instance.ornament_type else "X"

                instance.code = f"{name_letter}{sub_category}{main_category}{kaligar_letter}{ornament_type_letter}{instance.pk}"
            # else: keep existing non-empty code

        # For new objects, let the signal handle auto-generation

        if commit:
            try:
                # If editing existing ornament and no new image uploaded, preserve existing image
                if instance.pk and 'image' not in self.changed_data:
                    # No new image uploaded, save without touching image field
                    instance.save(update_fields=[f for f in self.changed_data if f != 'image'])
                else:
                    # New ornament or new image uploaded
                    instance.save()
            except Exception as e:
                # If Cloudinary connection fails (common on PythonAnywhere), try to save without the image
                error_msg = str(e)
                if any(keyword in error_msg.lower() for keyword in ['cloudinary', 'connection refused', 'max retries', 'errno 111', 'tcpkeepalive']):
                    # Clear the image field and try again
                    if hasattr(instance, 'image'):
                        old_image = instance.image
                        instance.image = None
                    instance.save()
                    # Store that image upload failed for view to handle
                    self._cloudinary_failed = True
                else:
                    # Re-raise other exceptions
                    raise

        return instance

    def clean_weight(self):
        weight = self.cleaned_data.get('weight')
        if weight is not None and weight < 0:
            raise ValidationError("Weight cannot be negative.")
        return weight

    def clean_diamond_weight(self):
        diamond_weight = self.cleaned_data.get('diamond_weight')
        if diamond_weight is not None and diamond_weight < 0:
            raise ValidationError("Stone weight cannot be negative.")
        return diamond_weight

    def clean_jarti(self):
        jarti = self.cleaned_data.get('jarti')

        if jarti in [None, ""]:
            return Decimal("0.000")

        if jarti < 0:
            raise ValidationError("Jarti cannot be negative.")

        return Decimal(jarti)

    def clean_jyala(self):
        jyala = self.cleaned_data.get('jyala')

        if jyala in [None, ""]:
            return Decimal("0.000")

        if jyala < 0:
            raise ValidationError("Jyala cannot be negative.")

        return Decimal(jyala)

    def clean_stone_weight(self):
        stone_weight = self.cleaned_data.get('stone_weight')

        if stone_weight in [None, ""]:
            return Decimal("0.000")

        if stone_weight < 0:
            raise ValidationError("Stone weight cannot be negative.")

        return Decimal(stone_weight)
