from django import forms
from django.core.exceptions import ValidationError
from nepali_datetime_field.forms import NepaliDateField
from decimal import Decimal
from .models import Ornament
import nepali_datetime as ndt


class OrnamentForm(forms.ModelForm):

    ornament_date = NepaliDateField(required=False)
    jarti = forms.DecimalField(
        max_digits=10,
        decimal_places=3,
        required=False
    )

    class Meta:
        model = Ornament
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Set default date to today's Nepali date for new instances
        if not self.instance.pk and not self.initial.get('ornament_date'):
            self.initial['ornament_date'] = ndt.date.today()

        # Code is auto-generated
        if 'code' in self.fields:
            self.fields['code'].required = False
            self.fields['code'].widget.attrs.update({
                'class': 'form-control bg-light',
                'placeholder': 'Code (auto-generated)',
            })

    def save(self, commit=True):
        """Preserve or backfill ornament code when saving.

        - New ornaments: code is generated by the post_save signal if blank.
        - Existing ornaments: keep existing code if present; if it's blank,
          generate a code based on the current field values and existing `pk`.
        """

        instance = super().save(commit=False)

        # For existing objects, ensure they have a code
        if instance.pk:
            if not instance.code:
                name_letter = instance.ornament_name[0].upper() if instance.ornament_name else "X"
                sub_category = instance.subcategory.name[0].upper() if instance.subcategory else "X"
                main_category = instance.maincategory.name[0].upper() if instance.maincategory else "X"
                kaligar_letter = instance.kaligar.name[0].upper() if instance.kaligar else "X"
                ornament_type_letter = instance.ornament_type[0].upper() if instance.ornament_type else "X"

                instance.code = f"{name_letter}{sub_category}{main_category}{kaligar_letter}{ornament_type_letter}{instance.pk}"
            # else: keep existing non-empty code

        # For new objects, let the signal handle auto-generation

        if commit:
            instance.save()

        return instance

    def clean_weight(self):
        weight = self.cleaned_data.get('weight')
        if weight is not None and weight < 0:
            raise ValidationError("Weight cannot be negative.")
        return weight

    def clean_diamond_weight(self):
        diamond_weight = self.cleaned_data.get('diamond_weight')
        if diamond_weight is not None and diamond_weight < 0:
            raise ValidationError("Stone weight cannot be negative.")
        return diamond_weight

    def clean_jarti(self):
        jarti = self.cleaned_data.get('jarti')

        if jarti in [None, ""]:
            return Decimal("0.000")

        if jarti < 0:
            raise ValidationError("Jarti cannot be negative.")

        return Decimal(jarti)
