# Generated by Django 5.0 on 2026-06-11 13:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('order_ready', 'Order Ready'), ('due_payment', 'Due Payment Reminder'), ('rate_alert', 'Rate Alert'), ('birthday', 'Birthday Campaign')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign Message Log',
                'verbose_name_plural': 'Campaign Message Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('sms_opt_in', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('order', 'Order'), ('import', 'Import')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Campaign Contact',
                'verbose_name_plural': 'Customer Campaign Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_date', models.CharField(help_text="Nepali date (e.g., '11 Poush 2082')", max_length=50)),
                ('gold_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per tola', max_digits=12)),
                ('silver_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Silver rate per tola', max_digits=12)),
                ('gold_rate_10g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per 10 grams', max_digits=12)),
                ('silver_rate_10g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Silver rate per 10 grams', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetalCategoryPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_enabled', models.BooleanField(default=True, help_text='Enable/disable special pricing for ALL gold items')),
                ('gold_fixed_jyala', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Fixed jyala amount (रु) to add to all gold item prices', max_digits=10)),
                ('silver_enabled', models.BooleanField(default=True, help_text='Enable/disable special pricing for ALL silver items')),
                ('silver_fixed_jyala', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Fixed jyala amount (रु) to add to all silver item prices', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Internal notes about metal pricing rules', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metal Category Pricing Config',
                'verbose_name_plural': 'Metal Category Pricing Configs',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Fiscal year (e.g., 2078, 2079)', unique=True)),
                ('diamond', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Diamond stock in grams', max_digits=10)),
                ('gold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Gold stock in grams', max_digits=10)),
                ('silver', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Silver stock in grams', max_digits=10)),
                ('jardi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Jardi amount in currency', max_digits=10)),
                ('wages', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wages amount in currency', max_digits=10)),
                ('gold_silver_rate_unit', models.CharField(choices=[('gram', 'Per Gram'), ('10gram', 'Per 10 Gram'), ('tola', 'Per Tola')], default='tola', help_text='Unit for gold and silver rates', max_length=10)),
                ('diamond_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diamond rate per gram', max_digits=12)),
                ('gold_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per tola', max_digits=12)),
                ('silver_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Silver rate per tola', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['-year'],
            },
        ),
    ]
