# Generated by Django 5.2 on 2025-12-25 17:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Fiscal year (e.g., 2078, 2079)', unique=True)),
                ('diamond', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Diamond stock in grams', max_digits=10)),
                ('gold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Gold stock in grams', max_digits=10)),
                ('silver', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Silver stock in grams', max_digits=10)),
                ('jardi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Jardi amount in currency', max_digits=10)),
                ('wages', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wages amount in currency', max_digits=10)),
                ('diamond_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diamond rate per gram', max_digits=12)),
                ('gold_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per gram', max_digits=12)),
                ('silver_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Silver rate per gram', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['-year'],
            },
        ),
    ]
