# Generated by Django 5.2.8 on 2025-12-24 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Diamond stock in grams', max_digits=10)),
                ('gold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Gold stock in grams', max_digits=10)),
                ('silver', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Silver stock in grams', max_digits=10)),
                ('jardi', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jardi stock in grams', max_digits=10)),
                ('wages', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wages amount in currency', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
