# Generated by Django 5.2.8 on 2025-12-26 07:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dailyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrate',
            name='bs_date',
            field=models.CharField(blank=True, help_text="Nepali date as shown on site, e.g., '11 Poush 2082'", max_length=50),
        ),
        migrations.AddField(
            model_name='dailyrate',
            name='gold_rate_10g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per 10 grams', max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyrate',
            name='silver_rate_10g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Silver rate per 10 grams', max_digits=12),
        ),
    ]
