# Generated by Django 5.2.8 on 2025-12-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stock_options_stock_diamond_rate_and_more'),
        ('main', '0002_stock_updates'),
    ]

    operations = [
    ]
