# Generated by Django 5.0 on 2026-06-14 08:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('home_hero', 'Customer Home — Main Hero Banner'), ('home_promo', 'Customer Home — Promo / Newsletter Banner'), ('shop_banner', 'Shop Page — Top Banner')], help_text='Which page section this image belongs to', max_length=50, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('tagline', models.CharField(blank=True, default='The Eternal Sparkle', help_text='Small text above the main title', max_length=120)),
                ('title', models.CharField(blank=True, default='Antique Gold Collections', help_text='Main headline on the banner', max_length=200)),
                ('button_text', models.CharField(blank=True, default='Shop Collection', help_text='Call-to-action button label', max_length=60)),
                ('is_active', models.BooleanField(default=True, help_text='When off, the default placeholder image and text are shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Page Image',
                'verbose_name_plural': 'Customer Page Images',
                'ordering': ['slot'],
            },
        ),
    ]
