# Generated by Django 5.2 on 2025-12-25 17:27

import django.core.validators
import django.db.models.deletion
import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('panno', models.CharField(help_text='Enter 9-digit PAN number.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_pan_digits', message='PAN No must be exactly 9 digits.', regex='^\\d{9}$')])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('party_name', 'panno'), name='unique_party_name_panno')],
            },
        ),
        migrations.CreateModel(
            name='GoldSilverPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=20, unique=True)),
                ('bill_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('particular', models.CharField(blank=True, max_length=255, null=True)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond')], default='gold', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('wages', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('fonepay', 'Fonepay')], default='cash', max_length=12)),
                ('is_paid', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(blank=True, help_text='Select the party for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_purchases', to='goldsilverpurchase.party')),
            ],
            options={
                'verbose_name': 'Gold/Silver Purchase',
                'verbose_name_plural': 'Gold/Silver Purchases',
                'ordering': ['-bill_date', '-created_at'],
                'indexes': [models.Index(fields=['bill_no'], name='goldsilverp_bill_no_5b8f2c_idx'), models.Index(fields=['party', 'bill_date'], name='goldsilverp_party_i_7164cf_idx'), models.Index(fields=['metal_type', 'bill_date'], name='goldsilverp_metal_t_f466e0_idx')],
            },
        ),
    ]
