# Generated by Django 5.0 on 2026-06-11 13:05

import django.core.validators
import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('purity', models.CharField(choices=[('24K', '24 Karat'), ('22K', '22 Karat'), ('18K', '18 Karat'), ('14K', '14 Karat')], default='22K', help_text='Purity/Karat of the metal', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=20, unique=True, verbose_name='SN')),
                ('bill_no', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('purchase_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond')], max_length=10)),
                ('ornament_name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Percentage of weight (e.g., for loss calculation)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Final weight after applying percentage', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('refined_status', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', help_text='Has this purchase been refined?', max_length=10, verbose_name='Refined')),
                ('refined_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight after refining (if applicable)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_unit', models.CharField(choices=[('gram', 'Per Gram'), ('10gram', 'Per 10 Gram'), ('tola', 'Per Tola')], default='tola', help_text='Unit for rate (per gram, per 10 gram, per tola)', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: Weight × Rate', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Diamond weight for diamond purchases', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('diamond_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate for diamond weight', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('diamond_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: Diamond Weight × Diamond Rate', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: Gold Amount + Diamond Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Auto-calculated: Refined Weight - Final Weight', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-999999.999'))])),
                ('profit', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: Profit Weight × Rate (adjusted for rate_unit)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-999999.99'))])),
            ],
        ),
        migrations.CreateModel(
            name='GoldSilverPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=20, unique=True)),
                ('bill_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('particular', models.CharField(blank=True, max_length=255, null=True)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond')], default='gold', max_length=10)),
                ('purity', models.CharField(choices=[('24K', '24 Karat'), ('22K', '22 Karat'), ('18K', '18 Karat'), ('14K', '14 Karat')], default='24K', help_text='Purity/Karat of the metal', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_unit', models.CharField(choices=[('gram', 'Per Gram'), ('10gram', 'Per 10 Gram'), ('tola', 'Per Tola')], default='tola', help_text='Unit for rate (per gram, per 10 gram, per tola)', max_length=10)),
                ('wages', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('fonepay', 'Fonepay')], default='cash', max_length=12)),
                ('is_paid', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gold/Silver Purchase',
                'verbose_name_plural': 'Gold/Silver Purchases',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], default='gold', max_length=10)),
                ('purity', models.CharField(choices=[('24K', '24 Karat'), ('22K', '22 Karat'), ('18K', '18 Karat'), ('14K', '14 Karat')], default='22K', help_text='Purity/Karat of the metal', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Weight in grams', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per selected unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_unit', models.CharField(choices=[('gram', 'Per Gram'), ('10gram', 'Per 10 Gram'), ('tola', 'Per Tola')], default='tola', help_text='Unit for rate (per gram, per 10 gram, per tola)', max_length=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: Quantity × Unit Cost', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(choices=[('GoldSilverPurchase', 'Gold/Silver Purchase'), ('CustomerPurchase', 'Customer Purchase')], default='GoldSilverPurchase', help_text='Source of this stock: Gold/Silver Purchase or Customer Purchase.', max_length=32)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about the stock', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metal Stock',
                'verbose_name_plural': 'Metal Stocks',
                'ordering': ['-last_updated', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetalStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Rate for this transaction (per selected unit)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment')], default='in', max_length=15)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Weight moved (in grams)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_type', models.CharField(blank=True, help_text='e.g., Purchase, Sale, Refinement, Conversion', max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Bill number or transaction ID', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('movement_date', nepali_datetime_field.models.NepaliDateField(blank=True, help_text='Date of the stock movement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metal Stock Movement',
                'verbose_name_plural': 'Metal Stock Movements',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetalStockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('raw', 'Raw'), ('refined', 'Refined'), ('scrap', 'Scrap'), ('other', 'Other')], max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Metal Stock Type',
                'verbose_name_plural': 'Metal Stock Types',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('panno', models.CharField(help_text='Enter 9-digit PAN number.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_pan_digits', message='PAN No must be exactly 9 digits.', regex='^\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='HomePagePerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(default='/', max_length=120)),
                ('source', models.CharField(default='customer_home', max_length=60)),
                ('ttfb_ms', models.FloatField(blank=True, null=True)),
                ('fcp_ms', models.FloatField(blank=True, null=True)),
                ('lcp_ms', models.FloatField(blank=True, null=True)),
                ('cls', models.FloatField(blank=True, null=True)),
                ('dom_content_loaded_ms', models.FloatField(blank=True, null=True)),
                ('load_event_ms', models.FloatField(blank=True, null=True)),
                ('resource_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('transfer_size_kb', models.FloatField(blank=True, null=True)),
                ('image_transfer_size_kb', models.FloatField(blank=True, null=True)),
                ('js_transfer_size_kb', models.FloatField(blank=True, null=True)),
                ('css_transfer_size_kb', models.FloatField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='goldsilverp_created_27777f_idx'), models.Index(fields=['source', 'created_at'], name='goldsilverp_source_81eea8_idx')],
            },
        ),
    ]
