# Generated by Django 5.0 on 2026-06-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goldsilverpurchase', '0001_initial'),
        ('ornament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalstockmovement',
            name='kaligar',
            field=models.ForeignKey(blank=True, help_text='Kaligar involved in this transaction (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ornament.kaligar'),
        ),
        migrations.AddField(
            model_name='metalstockmovement',
            name='metal_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='goldsilverpurchase.metalstock'),
        ),
        migrations.AddField(
            model_name='metalstock',
            name='stock_type',
            field=models.ForeignKey(help_text='Type of stock: Raw or Refined', on_delete=django.db.models.deletion.PROTECT, related_name='metal_stocks', to='goldsilverpurchase.metalstocktype'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('party_name', 'panno'), name='unique_party_name_panno'),
        ),
        migrations.AddField(
            model_name='goldsilverpurchase',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Select the party for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_purchases', to='goldsilverpurchase.party'),
        ),
        migrations.AddIndex(
            model_name='metalstockmovement',
            index=models.Index(fields=['metal_stock', 'movement_date'], name='goldsilverp_metal_s_ceb0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='metalstockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='goldsilverp_referen_14a65b_idx'),
        ),
        migrations.AddIndex(
            model_name='metalstock',
            index=models.Index(fields=['metal_type', 'stock_type'], name='goldsilverp_metal_t_855ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='metalstock',
            index=models.Index(fields=['metal_type', 'purity'], name='goldsilverp_metal_t_9745d0_idx'),
        ),
        migrations.AddIndex(
            model_name='metalstock',
            index=models.Index(fields=['stock_type'], name='goldsilverp_stock_t_5e1324_idx'),
        ),
        migrations.AddIndex(
            model_name='goldsilverpurchase',
            index=models.Index(fields=['bill_no'], name='goldsilverp_bill_no_5b8f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='goldsilverpurchase',
            index=models.Index(fields=['party', 'bill_date'], name='goldsilverp_party_i_7164cf_idx'),
        ),
        migrations.AddIndex(
            model_name='goldsilverpurchase',
            index=models.Index(fields=['metal_type', 'bill_date'], name='goldsilverp_metal_t_f466e0_idx'),
        ),
    ]
