# Generated by Django 5.2.8 on 2025-11-22 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldsilverpurchase',
            name='panno',
            field=models.CharField(blank=True, help_text='Indian PAN (10 chars).', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_pan', message='PAN must be 10 chars: 5 letters, 4 digits, 1 letter (e.g., ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
