# Generated by Django 5.2 on 2025-11-23 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0002_alter_goldsilverpurchase_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
