# Generated by Django 5.2.8 on 2025-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0002_goldsilverpurchase_panno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='panno',
            field=models.IntegerField(),
        ),
    ]
