# Generated by Django 5.2 on 2025-11-23 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0003_alter_goldsilverpurchase_wages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
