# Generated by Django 5.2.8 on 2025-11-22 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0003_alter_goldsilverpurchase_panno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='panno',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
