# Generated by Django 5.2 on 2025-11-23 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0004_alter_goldsilverpurchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='wages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
