# Generated by Django 5.2.8 on 2025-11-22 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0004_alter_goldsilverpurchase_panno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='panno',
            field=models.PositiveBigIntegerField(help_text='10-digit PAN number (digits only).', validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
