# Generated by Django 5.2.8 on 2025-11-22 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0005_alter_goldsilverpurchase_panno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='panno',
            field=models.CharField(blank=True, help_text='Enter 9-digit PAN number.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_pan_digits', message='PAN No must be exactly 9 digits.', regex='^\\d{9}$')]),
        ),
    ]
