# Generated by Django 5.2 on 2025-11-29 18:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0005_alter_goldsilverpurchase_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='wages',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
