# Generated by Django 5.2.8 on 2025-12-05 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0006_alter_goldsilverpurchase_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('panno', models.CharField(help_text='Enter 9-digit PAN number.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_pan_digits', message='PAN No must be exactly 9 digits.', regex='^\\d{9}$')])),
            ],
        ),
    ]
