# Generated by Django 5.2.8 on 2025-12-05 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0007_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldsilverpurchase',
            name='panno',
        ),
        migrations.RemoveField(
            model_name='goldsilverpurchase',
            name='particular',
        ),
        migrations.RemoveField(
            model_name='goldsilverpurchase',
            name='party_name',
        ),
        migrations.AddField(
            model_name='goldsilverpurchase',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Select the party for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_purchases', to='goldsilverpurchase.party'),
        ),
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='metal_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='gold', max_length=6),
        ),
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
