# Generated by Django 5.2.8 on 2025-12-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0008_remove_goldsilverpurchase_panno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='particulars',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
