# Generated by Django 5.2.8 on 2025-12-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0009_alter_goldsilverpurchase_particulars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldsilverpurchase',
            old_name='particulars',
            new_name='particular',
        ),
    ]
