# Generated by Django 5.2.8 on 2025-12-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0010_rename_particulars_goldsilverpurchase_particular'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('party_name', 'panno'), name='unique_party_name_panno'),
        ),
    ]
