# Generated by Django 5.2.1 on 2025-12-05 16:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0011_party_unique_party_name_panno'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldsilverpurchase',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
