# Generated by Django 5.2 on 2025-12-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldsilverpurchase', '0012_goldsilverpurchase_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldsilverpurchase',
            options={'ordering': ['-bill_date', '-created_at'], 'verbose_name': 'Gold/Silver Purchase', 'verbose_name_plural': 'Gold/Silver Purchases'},
        ),
        migrations.AddField(
            model_name='goldsilverpurchase',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goldsilverpurchase',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='metal_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('diamond', 'Diamond')], default='gold', max_length=10),
        ),
        migrations.AlterField(
            model_name='goldsilverpurchase',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('fonepay', 'Fonepay')], default='cash', max_length=12),
        ),
        migrations.AddIndex(
            model_name='goldsilverpurchase',
            index=models.Index(fields=['bill_no'], name='goldsilverp_bill_no_5b8f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='goldsilverpurchase',
            index=models.Index(fields=['party', 'bill_date'], name='goldsilverp_party_i_7164cf_idx'),
        ),
        migrations.AddIndex(
            model_name='goldsilverpurchase',
            index=models.Index(fields=['metal_type', 'bill_date'], name='goldsilverp_metal_t_f466e0_idx'),
        ),
    ]
