from django.urls import path
from .views import (
    PartyCreateView, PurchaseListView, PurchaseCreateView,
    PurchaseUpdateView, PurchaseDeleteView,
    CustomerPurchaseListView, CustomerPurchaseCreateView,
    CustomerPurchaseUpdateView, CustomerPurchaseDeleteView,
    export_excel, print_view, import_excel,
    export_customer_excel, import_customer_excel,
    data_settings, export_all_data, export_all_data_json, import_all_data_json,
    import_wizard, import_wizard_process,
    MetalStockListView, metal_stock_detail,
    MetalStockCreateView, MetalStockUpdateView, MetalStockDeleteView,
    MetalStockMovementCreateView, MetalStockMovementUpdateView, MetalStockMovementDeleteView,
    export_metalstock_xlsx, ImportMetalStockXLSXView,
)

app_name = 'gsp'

urlpatterns = [
    path('', PurchaseListView.as_view(), name='purchaselist'),
    path('create/', PurchaseCreateView.as_view(), name='createpurchase'),
    path('createparty/', PartyCreateView.as_view(), name='createparty'),
    path('<int:pk>/edit/', PurchaseUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PurchaseDeleteView.as_view(), name='delete'),
    path('customer-purchases/', CustomerPurchaseListView.as_view(), name='customer_purchase_list'),
    path('customer-purchases/create/', CustomerPurchaseCreateView.as_view(), name='customer_purchase_create'),
    path('customer-purchases/<int:pk>/edit/', CustomerPurchaseUpdateView.as_view(), name='customer_purchase_update'),
    path('customer-purchases/<int:pk>/delete/', CustomerPurchaseDeleteView.as_view(), name='customer_purchase_delete'),
    path('customer-purchases/export-excel/', export_customer_excel, name='customer_export_excel'),
    path('customer-purchases/import-excel/', import_customer_excel, name='customer_import_excel'),
    path("print/", print_view, name="print_view"),
    path("export-excel/", export_excel, name="export_excel"),
    path('import-excel/', import_excel, name='gsp_import_excel'),
    path('data-settings/', data_settings, name='data_settings'),
    path('export-all-data/', export_all_data, name='export_all_data'),
    path('export-all-data-json/', export_all_data_json, name='export_all_data_json'),
    path('import-all-data-json/', import_all_data_json, name='import_all_data_json'),
    path('import-wizard/', import_wizard, name='import_wizard'),
    path('import-wizard/process/', import_wizard_process, name='import_wizard_process'),
    path('metal-stock/', MetalStockListView.as_view(), name='metal_stock_list'),
    path('metal-stock/create/', MetalStockCreateView.as_view(), name='metal_stock_create'),
    path('metal-stock/<int:pk>/', metal_stock_detail, name='metal_stock_detail'),
    path('metal-stock/<int:pk>/edit/', MetalStockUpdateView.as_view(), name='metal_stock_update'),
    path('metal-stock/<int:pk>/delete/', MetalStockDeleteView.as_view(), name='metal_stock_delete'),
    path('metal-stock/<int:stock_pk>/add-transaction/', MetalStockMovementCreateView.as_view(), name='metal_stock_add_transaction'),
    path('metal-stock/movement/<int:pk>/edit/', MetalStockMovementUpdateView.as_view(), name='metal_stock_movement_edit'),
    path('metal-stock/movement/<int:pk>/delete/', MetalStockMovementDeleteView.as_view(), name='metal_stock_movement_delete'),
    path('metal-stock/export-xlsx/', export_metalstock_xlsx, name='metal_stock_export_xlsx'),
    path('metal-stock/import-xlsx/', ImportMetalStockXLSXView.as_view(), name='metal_stock_import_xlsx'),
]
