# Generated by Django 5.0 on 2026-06-11 13:05

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaligar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('panno', models.CharField(help_text='Enter 9-digit PAN number.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_pan_digits', message='PAN No must be exactly 9 digits.', regex='^\\d{9}$')])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('stamp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motimala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_per_mala', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_per_mala', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Potey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loon', models.PositiveIntegerField()),
                ('cost_per_loon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_per_loon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_per_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_per_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kaligar_CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('particular', models.CharField(max_length=255)),
                ('amount_taken', models.IntegerField()),
                ('to_pay', models.IntegerField()),
                ('provided_by', models.CharField(max_length=255)),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='ornament.kaligar')),
            ],
        ),
        migrations.CreateModel(
            name='Kaligar_GoldAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('gold_deposit', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_loss', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_remaining', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_accounts', to='ornament.kaligar')),
            ],
        ),
        migrations.CreateModel(
            name='Kaligar_LossReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('gold_loss', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_return', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_returns', to='ornament.kaligar')),
            ],
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornament_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code / नं.')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barcode')),
                ('metal_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Others', 'Others')], default='Gold', max_length=50)),
                ('type', models.CharField(choices=[('24KARAT', '24 Karat'), ('23KARAT', '23 Karat'), ('22KARAT', '22 Karat'), ('18KARAT', '18 Karat'), ('14KARAT', '14 Karat')], default='24KARAT', max_length=10, verbose_name='किसिम')),
                ('ornament_type', models.CharField(choices=[('stock', 'Stock'), ('order', 'Order'), ('sales', 'Sales')], default='stock', max_length=10, verbose_name='गहनाको किसिम')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('destroyed', 'Destroyed')], default='active', help_text='Active, Deleted, or Destroyed', max_length=10, verbose_name='Status')),
                ('ornament_name', models.CharField(max_length=255, verbose_name='गहना')),
                ('gross_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Gross Weight (तोल)')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Metal Weight (तोल)')),
                ('diamond_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Diamond Weight (हिरा / पत्थर तौल)')),
                ('diamond_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate used for diamond valuation', max_digits=12, verbose_name='Diamond Rate (per gram)')),
                ('zircon_weight', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True, verbose_name='Zircon Weight')),
                ('stone_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Stone Weight (पत्थर तौल)')),
                ('stone_percaratprice', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Stone Price')),
                ('stone_totalprice', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Stone Price')),
                ('jarti', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('jyala', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('barcode_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Barcode Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ornaments', to='ornament.kaligar')),
                ('maincategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ornament.maincategory')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ornaments', to='order.order')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ornament.subcategory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kaligar_Ornaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('gold_given', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ornament_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('jarti', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_return', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_loss', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_purity', models.CharField(choices=[('24KARAT', '24 Karat'), ('22KARAT', '22 Karat'), ('18KARAT', '18 Karat'), ('14KARAT', '14 Karat')], default='24KARAT', max_length=10, verbose_name='किसिम')),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaligar_ornaments', to='ornament.kaligar')),
                ('ornament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaligar_work_records', to='ornament.ornament')),
            ],
        ),
    ]
