# Generated by Django 5.2 on 2025-12-01 15:52

import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornament_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True, verbose_name='मिति')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code / नं.')),
                ('ornament_name', models.CharField(max_length=255, verbose_name='गहना')),
                ('type', models.CharField(choices=[('24KARAT', '24 Karat'), ('22KARAT', '22 Karat'), ('18KARAT', '18 Karat'), ('14KARAT', '14 Karat')], default='24KARAT', max_length=10, verbose_name='किसिम')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Metal Weight (तोल)')),
                ('diamond_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name=' Diamond Weight (हिरा / पत्थर तौल)')),
                ('jarti', models.CharField(blank=True, max_length=50, verbose_name='जर्ती')),
                ('kaligar', models.CharField(blank=True, max_length=100, verbose_name='कसियार')),
                ('ornament_type', models.CharField(choices=[('stock', 'Stock'), ('order', 'Order')], default='stock', max_length=10, verbose_name='गहनाको किसिम')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='ग्राहकको नाम')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
