# Generated by Django 5.2.8 on 2025-12-09 07:32

import django.core.validators
import django.db.models.deletion
import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_delete_ornament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaligar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('panno', models.CharField(help_text='Enter 9-digit PAN number.', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_pan_digits', message='PAN No must be exactly 9 digits.', regex='^\\d{9}$')])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('stamp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kaligar_CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('particular', models.CharField(max_length=255)),
                ('amount_taken', models.IntegerField()),
                ('to_pay', models.IntegerField()),
                ('provided_by', models.CharField(max_length=255)),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='ornament.kaligar')),
            ],
        ),
        migrations.CreateModel(
            name='Kaligar_GoldAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('gold_deposit', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_loss', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_remaining', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_accounts', to='ornament.kaligar')),
            ],
        ),
        migrations.CreateModel(
            name='Kaligar_Ornaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('gold_given', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ornament_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('jarti', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_return', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_loss', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gold_purity', models.CharField(choices=[('24KARAT', '24 Karat'), ('22KARAT', '22 Karat'), ('18KARAT', '18 Karat'), ('14KARAT', '14 Karat')], default='24KARAT', max_length=10, verbose_name='किसिम')),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaligar_ornaments', to='ornament.kaligar')),
            ],
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornament_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('metal_type', models.CharField(choices=[('Gold', 'gold'), ('Silver', 'silver'), ('Diamond', 'diamond'), ('Others', 'others')], default='Gold', max_length=50, null=True)),
                ('type', models.CharField(choices=[('24KARAT', '24 Karat'), ('22KARAT', '22 Karat'), ('18KARAT', '18 Karat'), ('14KARAT', '14 Karat')], default='24KARAT', max_length=10, verbose_name='किसिम')),
                ('ornament_type', models.CharField(choices=[('stock', 'Stock'), ('order', 'Order')], default='stock', max_length=10, verbose_name='गहनाको किसिम')),
                ('ornament_name', models.CharField(max_length=255, verbose_name='गहना')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Metal Weight (तोल)')),
                ('diamond_weight', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True, verbose_name='Diamond Weight (हिरा / पत्थर तौल)')),
                ('jarti', models.CharField(blank=True, max_length=50, verbose_name='जर्ती')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kaligar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ornaments', to='ornament.kaligar')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
    ]
