# Generated by Django 5.2 on 2025-12-02 16:52

import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ornament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornament',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code / नं.'),
        ),
        migrations.AlterField(
            model_name='ornament',
            name='ornament_date',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
    ]
