# Generated by Django 5.2.8 on 2025-12-09 07:50

import django.core.validators
import django.db.models.deletion
import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ornament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornament',
            name='code',
            field=models.CharField(max_length=50, null=True, blank=True, unique=True, verbose_name='Code / नं.'),
        ),
    ]
