# Generated by Django 5.2.8 on 2025-12-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delete_ornament'),
        ('ornament', '0002_alter_ornament_code_alter_ornament_ornament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornament',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ornaments', to='order.order'),
        ),
    ]
