# Generated by Django 5.2.8 on 2025-12-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ornament', '0002_add_code_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornament',
            name='metal_type',
            field=models.CharField(choices=[('Gold', 'gold'), ('Silver', 'silver'), ('Diamond', 'diamond'), ('Others', 'others')], default='Gold', max_length=50),
        ),
    ]
