# Generated by Django 5.2.8 on 2025-12-09 16:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ornament', '0004_maincategory_subcategory_ornament_maincategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornament',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
