# Generated by Django 5.2 on 2025-11-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('deliver_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('ornament_name', models.CharField(max_length=255)),
                ('ornament_type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jarti', models.CharField(blank=True, max_length=255, null=True)),
                ('jyala', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('stone', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=10)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=10)),
            ],
        ),
    ]
