# Generated by Django 5.0 on 2026-06-11 13:05

import django.core.validators
import django.db.models.deletion
import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('goldsilverpurchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('deliver_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number (optional)', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Customer address (optional)', null=True)),
                ('phone_number', models.CharField(help_text='Enter a valid phone number (7-15 digits).', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be 7-15 digits.', regex='^\\d{7,15}$')])),
                ('status', models.CharField(choices=[('order', 'Order'), ('processing', 'Processing'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='order', max_length=10)),
                ('order_type', models.CharField(choices=[('custom', 'Custom'), ('standard', 'Standard'), ('repair', 'Repair'), ('remake', 'Remake')], default='custom', help_text='Type of order', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional notes or description for the order', null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount of all ornaments before discount', max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, help_text='Taxable amount (gold and diamond ornaments only, excluding silver)', max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal after discount and before tax', max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('gold', 'Gold'), ('silver', 'Silver'), ('sundry_debtor', 'Sundry Debtor'), ('mixed', 'Mixed')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number (optional)', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Customer address (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'order_sale',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment')], default='invoice', help_text='Type of transaction: invoice creates balance, payment reduces it', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debtor', models.ForeignKey(blank=True, help_text='The sundry debtor making this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to='finance.sundrydebtor')),
            ],
            options={
                'verbose_name': 'Debtor Payment',
                'verbose_name_plural': 'Debtor Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMetalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_unit', models.CharField(choices=[('gram', 'Per Gram'), ('10gram', 'Per 10 Gram'), ('tola', 'Per Tola')], default='gram', help_text='Unit for rate (per gram, per 10 gram, per tola)', max_length=10)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], default='gold', help_text='Type of metal', max_length=10)),
                ('purity', models.CharField(choices=[('24K', '24 Karat'), ('22K', '22 Karat'), ('18K', '18 Karat'), ('14K', '14 Karat')], default='24K', help_text='Purity/Karat of the metal', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity in grams', max_digits=12)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per gram at the time of order', max_digits=12)),
                ('line_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: Quantity × Rate per gram', max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about this metal item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='order_metals', to='order.order')),
                ('stock_type', models.ForeignKey(blank=True, help_text='Type of stock: Raw, Refined, Scrap, Other', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_metal_stocks', to='goldsilverpurchase.metalstocktype')),
            ],
            options={
                'verbose_name': 'Order Metal Stock',
                'verbose_name_plural': 'Order Metal Stocks',
            },
        ),
        migrations.CreateModel(
            name='OrderOrnament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per unit', max_digits=10)),
                ('diamond_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diamond rate per unit', max_digits=10)),
                ('zircon_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zircon rate per unit', max_digits=10)),
                ('stone_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stone rate per unit', max_digits=10)),
                ('jarti', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jarti amount', max_digits=10)),
                ('own_gold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Customer provided own gold to deduct from net weight', max_digits=10)),
                ('jyala', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jyala amount', max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total for this ornament on this order', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ornaments', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Ornament',
                'verbose_name_plural': 'Order Ornaments',
            },
        ),
    ]
