# Generated by Django 5.2.8 on 2025-12-26 06:13

import django.core.validators
import django.db.models.deletion
import nepali_datetime_field.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ornament', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('deliver_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(help_text='Enter a valid phone number (7-15 digits).', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be 7-15 digits.', regex='^\\d{7,15}$')])),
                ('status', models.CharField(choices=[('order', 'Order'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='order', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount of all ornaments before discount', max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal after discount and before tax', max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderOrnament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per unit', max_digits=10)),
                ('diamond_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diamond rate per unit', max_digits=10)),
                ('zircon_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zircon rate per unit', max_digits=10)),
                ('stone_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stone rate per unit', max_digits=10)),
                ('jarti', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jarti amount', max_digits=10)),
                ('jyala', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jyala amount', max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total for this ornament on this order', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ornaments', to='order.order')),
                ('ornament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='ornament.ornament')),
            ],
            options={
                'verbose_name': 'Order Ornament',
                'verbose_name_plural': 'Order Ornaments',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='order.order')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'order_sale',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
