# Generated by Django 5.2 on 2025-12-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('ornament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderornament',
            name='ornament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='ornament.ornament'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='order.order'),
        ),
    ]
