# Generated by Django 5.2 on 2025-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order', 'Order'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='order', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('fonepay', 'Fonepay'), ('bank', 'Bank'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=10),
        ),
    ]
