# Generated by Django 5.2.8 on 2025-12-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ornament',
        ),
    ]
