# Generated by Django 5.0 on 2026-06-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('ornament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderornament',
            name='ornament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='ornament.ornament'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order'),
        ),
        migrations.AddField(
            model_name='debtorpayment',
            name='order_payment',
            field=models.OneToOneField(help_text='The order payment this debtor payment is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='debtor_payment', to='order.orderpayment'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='order.order'),
        ),
        migrations.AddIndex(
            model_name='ordermetalstock',
            index=models.Index(fields=['order', 'metal_type'], name='order_order_order_i_7cb830_idx'),
        ),
    ]
