# Generated by Django 5.2.8 on 2025-12-17 11:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diamond_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diamond rate per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='gold_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='jarti',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jarti amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='jyala',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jyala amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='stone_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stone rate per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax and discount', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='zircon_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zircon rate per unit', max_digits=10),
        ),
    ]
