# Generated by Django 5.2.8 on 2025-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_diamond_rate_order_discount_order_gold_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='calculate amount of all ornaments', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
