# Generated by Django 5.2.1 on 2025-12-18 17:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_amount_alter_order_subtotal'),
        ('ornament', '0011_alter_ornament_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='diamond_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gold_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='jarti',
        ),
        migrations.RemoveField(
            model_name='order',
            name='jyala',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stone_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zircon_rate',
        ),
        migrations.CreateModel(
            name='OrderOrnament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gold rate per unit', max_digits=10)),
                ('diamond_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Diamond rate per unit', max_digits=10)),
                ('zircon_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Zircon rate per unit', max_digits=10)),
                ('stone_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stone rate per unit', max_digits=10)),
                ('jarti', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jarti amount', max_digits=10)),
                ('jyala', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Jyala amount', max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total for this ornament on this order', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ornaments', to='order.order')),
                ('ornament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='ornament.ornament')),
            ],
            options={
                'verbose_name': 'Order Ornament',
                'verbose_name_plural': 'Order Ornaments',
            },
        ),
    ]
