# Generated by Django 5.2.8 on 2025-12-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bill_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
