# Generated by Django 5.2.8 on 2025-12-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_sale_bill_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sale',
            table='order_sale',
        ),
    ]
