# Generated by Django 5.0 on 2026-06-11 13:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goldsilverpurchase', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMetalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_unit', models.CharField(choices=[('gram', 'Per Gram'), ('10gram', 'Per 10 Gram'), ('tola', 'Per Tola')], default='gram', help_text='Unit for rate (per gram, per 10 gram, per tola)', max_length=10)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], default='gold', help_text='Type of metal', max_length=10)),
                ('purity', models.CharField(choices=[('24K', '24 Karat'), ('22K', '22 Karat'), ('18K', '18 Karat'), ('14K', '14 Karat')], default='24K', help_text='Purity/Karat of the metal', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity in grams', max_digits=12)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per gram at the time of sale', max_digits=12)),
                ('line_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: Quantity × Rate per gram', max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about this metal item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='sale_metals', to='order.sale')),
                ('stock_type', models.ForeignKey(blank=True, help_text='Type of stock: Raw, Refined, Scrap, Other', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_metal_stocks', to='goldsilverpurchase.metalstocktype')),
            ],
            options={
                'verbose_name': 'Sales Metal Stock',
                'verbose_name_plural': 'Sales Metal Stocks',
                'indexes': [models.Index(fields=['sale', 'metal_type'], name='sales_sales_sale_id_da2f52_idx')],
            },
        ),
    ]
